valtech-ch/saas-aem-module

- lombok.config
- set config to exclude lombok classes from test coverage
> add lombok.config file

- api/src/main/java/com/valtech/aem/saas/api/fulltextsearch/SearchModel.java
- core/src/main/java/com/valtech/aem/saas/core/fulltextsearch/SearchModelImpl.java
- core/src/test/java/com/valtech/aem/saas/core/autocomplete/AutocompleteServletTest.java
- core/src/test/java/com/valtech/aem/saas/core/fulltextsearch/SearchModelImplTest.java
- add the auto suggest url in the search config json
- update unit test
> ICSAAS-360 add autosuggestUrl property in search config json

- pom.xml
> ICSAAS-000 change protocol for developerConnection url

- core/src/main/java/com/valtech/aem/saas/core/fulltextsearch/SearchTabModelImpl.java
- core/src/test/java/com/valtech/aem/saas/core/fulltextsearch/SearchTabModelImplTest.java
- resolve starting offset from
- update unit test
> ICSAAS-374 update pagination param resolution

- api/src/main/java/com/valtech/aem/saas/api/fulltextsearch/SearchModel.java
- core/src/main/java/com/valtech/aem/saas/core/fulltextsearch/SearchModelImpl.java
- core/src/test/java/com/valtech/aem/saas/core/fulltextsearch/SearchModelImplTest.java
- core/src/test/java/com/valtech/aem/saas/core/fulltextsearch/SearchTabModelImplTest.java
- ui.apps/src/main/content/jcr_root/apps/saas-aem-module/i18n/en.json
- add suggestion text (i18n with a placeholder for the suggested text)
- add i18n entry
- add "no results found" text, to be displayed when no results have been found.
- add i18n entry
> ICSAAS-372 update search component

- LICENSE
remove old license
add new MIT license
> Change from Apache 2 to MIT license

- README.md
- introduction
- technical approach
> readme-introduction

- core/src/main/java/com/valtech/aem/saas/core/fulltextsearch/SearchTabModelImpl.java
- ui.frontend/src/main/webpack/site/js/components/loadMoreButton.ts
- ui.frontend/src/main/webpack/site/js/components/searchResultsTab.ts
- fix BE logic that sets the showLoadMoreButton flag
- fix FE due to change of "start" param default value
> ICSAAS-383 fix load more

- ui.frontend/src/main/webpack/site/js/components/searchItem.ts
- the entire result item should be a link (instead of a separate text link inside the item)
> ICSAAS-385 fix search result item link

- api/src/main/java/com/valtech/aem/saas/api/query/TypeaheadSearchTextParser.java
- api/src/main/java/com/valtech/aem/saas/api/query/TypeaheadTextQuery.java
- api/src/test/java/com/valtech/aem/saas/api/query/TypeaheadSearchTextParserTest.java
- revert to version that returns sensible results
> ICSAAS-384 fix typeahead query generating logic

- ui.apps/src/main/content/jcr_root/apps/saas-aem-module/clientlibs/wknd-sample/.content.xml
- ui.apps/src/main/content/jcr_root/apps/saas-aem-module/clientlibs/wknd-sample/css.txt
- ui.apps/src/main/content/jcr_root/apps/saas-aem-module/clientlibs/wknd-sample/css/styles.css
- add first draft of css styles
> ICSAAS-359 search demo sample css

- api/src/main/java/com/valtech/aem/saas/api/bestbets/dto/BestBetDTO.java
- update response DTO for getBestBets method, to comply with the SaaS change (https://tracking.valtech.swiss/browse/ICSAAS-356)
- rename property identifier to index
> ICSAAS-366 update best bets DTO

- api/src/main/java/com/valtech/aem/saas/api/bestbets/BestBetsService.java
- core/src/main/java/com/valtech/aem/saas/core/bestbets/DefaultBestBetsService.java
- core/src/main/java/com/valtech/aem/saas/core/http/response/BestBetIdDataExtractionStrategy.java
- core/src/test/java/com/valtech/aem/saas/core/bestbets/DefaultBestBetsServiceTest.java
- core/src/test/java/com/valtech/aem/saas/core/http/response/BestBetIdDataExtractionStrategyTest.java
- core/src/test/resources/__files/search/bestbets/addBestBetResponse.json
- update to fetch added best bet id
> ICSAAS-0000 update addBestBet endpoint

- ui.frontend/src/main/webpack/site/js/buildSearch.ts
- fix broken tab navigation (for the case when a page reload, with prefilled query term, is performed)
> ICSAAS-370 fix tab navigation issue

- api/src/main/java/com/valtech/aem/saas/api/fulltextsearch/SearchTabModel.java
- core/src/main/java/com/valtech/aem/saas/core/fulltextsearch/SearchTabModelImpl.java
- core/src/test/java/com/valtech/aem/saas/core/fulltextsearch/SearchTabModelImplTest.java
- ui.frontend/src/main/webpack/site/js/components/buildFacet.ts
- ui.frontend/src/main/webpack/site/js/components/loadMoreButton.ts
- ui.frontend/src/main/webpack/site/js/components/searchResultsTab.ts
- ui.frontend/src/main/webpack/site/js/utils/fetchSearch.ts
- rename query param to implementation suitable name ("start" -> "page")
> ICSAAS-377 rename pagination query param

- core/src/main/java/com/valtech/aem/saas/core/http/client/DefaultSearchRequestExecutorService.java
- core/src/main/java/com/valtech/aem/saas/core/http/response/dto/FallbackHighlightingDTO.java
- fix critical bug - findbugs:IS2_INCONSISTENT_SYNC
- remove code smell - avoid synchronized method modifier
> ICASAAS-0000 fix cloud-manager reported bugs

- api/src/main/java/com/valtech/aem/saas/api/fulltextsearch/SearchModel.java
- api/src/main/java/com/valtech/aem/saas/api/fulltextsearch/SearchRedirectModel.java
- core/src/main/java/com/valtech/aem/saas/core/fulltextsearch/SearchModelImpl.java
- core/src/main/java/com/valtech/aem/saas/core/fulltextsearch/SearchRedirectModelImpl.java
- core/src/main/java/com/valtech/aem/saas/core/util/ResourceUtil.java
- core/src/test/java/com/valtech/aem/saas/core/fulltextsearch/SearchModelImplTest.java
- core/src/test/java/com/valtech/aem/saas/core/fulltextsearch/SearchRedirectModelImplTest.java
- ui.frontend/src/main/webpack/site/js/__tests__/searchElement.spec.ts
- ui.frontend/src/main/webpack/site/js/buildSearch.ts
- ui.frontend/src/main/webpack/site/js/components/searchInput.ts
- ui.frontend/src/main/webpack/site/js/searchElement.ts
- ui.frontend/src/main/webpack/site/js/types/searchOptions.ts
- generate a unique id from a resource's path
- expose id in exported json model
- render search imput element with unique id
> ICSAAS-0000 fix unique html element id issue

- ui.frontend/src/main/webpack/site/js/components/searchForm.ts
> ICSAAS-0000 fix search redirect issue

- api/src/main/java/com/valtech/aem/saas/api/bestbets/dto/BestBetDTO.java
- core/src/test/java/com/valtech/aem/saas/core/http/response/BestBetsDataExtractionStrategyTest.java
- core/src/test/resources/__files/search/bestbets/getBestBets.json
- update according DTO
- index is of type String
- update unit test
> ICSAAS-396 fix BestBetsService::getBestBets

- core/src/main/java/com/valtech/aem/saas/core/http/client/DefaultSearchRequestExecutorService.java
- core/src/main/java/com/valtech/aem/saas/core/http/client/HttpResponseParser.java
- fix logic for re-use of content input stream
> ICSAAS-393 fix response content reading when debug level is enabled

- ui.frontend/src/main/webpack/site/js/components/searchForm.ts
- add check to add not-found element if it does not already exist
> ICSAAS-0000 not found message added multiple times

- core/src/main/java/com/valtech/aem/saas/core/bestbets/DefaultBestBetsService.java
- core/src/main/java/com/valtech/aem/saas/core/fulltextsearch/DefaultFulltextSearchService.java
- core/src/main/java/com/valtech/aem/saas/core/http/client/DefaultSearchServiceConnectionConfigurationService.java
- core/src/main/java/com/valtech/aem/saas/core/indexing/DefaultIndexUpdateService.java
- core/src/main/java/com/valtech/aem/saas/core/indexing/PageIndexUpdateHandler.java
- core/src/main/java/com/valtech/aem/saas/core/typeahead/DefaultTypeaheadService.java
- add configurationPid to each osgi cmp that is designated with an ocd
- set value to of osgi cmp class's fully qualified type name
> ICSAAS-397 fix osgi components configuration binding issue

- pom.xml
> ICSAAS-0000 update developer info (update email address)

- core/src/main/java/com/valtech/aem/saas/core/http/client/DefaultSearchRequestExecutorService.java
- core/src/main/java/com/valtech/aem/saas/core/http/client/DefaultSearchServiceConnectionConfigurationService.java
- core/src/main/java/com/valtech/aem/saas/core/http/client/JWTHttpRequestExecutor.java
- core/src/main/java/com/valtech/aem/saas/core/http/client/SearchServiceConnectionConfigurationService.java
- core/src/test/java/com/valtech/aem/saas/core/http/client/JWTHttpRequestExecutorTest.java
- update DefaultSearchRequestExecutorService
- add osgi config fields for jwt auth (will remove basic auth when jwt tested successfully)
> ICSAAS-411 migrate to jwt authentication

- ui.frontend/src/main/webpack/site/js/components/buildFacet.ts
- ui.frontend/src/main/webpack/site/js/components/loadMoreButton.ts
- ui.frontend/src/main/webpack/site/js/components/searchResults.ts
Wrap results items in a div, just so we can easily layout them. Facets are prepended to the searchResults element. So it should not be affected. They are already wrapped.
> refactor(ICSAAS-395): move results items in a wrapper

- api/src/main/java/com/valtech/aem/saas/api/query/SimpleFilter.java
- api/src/test/java/com/valtech/aem/saas/api/query/CompositeFilterTest.java
- api/src/test/java/com/valtech/aem/saas/api/query/SimpleFilterTest.java
- core/src/test/java/com/valtech/aem/saas/core/fulltextsearch/FilterConfigurationModelTest.java
- core/src/test/resources/content/components/searchtab/filters/content.json
- fix filter value (wrap with quites if contains whitespaces)
- update unit tests
> ICSAAS-430 fix no result when facet filter value is with whitespaces

- api/src/main/java/com/valtech/aem/saas/api/resource/PathTransformer.java
- core/src/main/java/com/valtech/aem/saas/core/http/client/DefaultSearchAdminRequestExecutorService.java
- core/src/main/java/com/valtech/aem/saas/core/indexing/PageIndexUpdateHandler.java
- core/src/main/java/com/valtech/aem/saas/core/resource/DefaultPathTransformer.java
- core/src/test/java/com/valtech/aem/saas/core/indexing/PageIndexUpdateHandlerTest.java
- core/src/test/java/com/valtech/aem/saas/core/resource/MockPathTransformer.java
- ui.config/src/main/content/jcr_root/apps/saas-aem-module/osgiconfig/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-saas-content-reader-service.cfg.json
- fix issues in DefaultPathTransformer
- fix issue in DefaultSearchAdminRequestExecutorService
- fix service mapping config
> Fixing PageIndexUpdateHandle

- README.md
- api/src/main/java/com/valtech/aem/saas/api/caconfig/SearchCAConfigurationModel.java
- api/src/main/java/com/valtech/aem/saas/api/caconfig/SearchConfiguration.java
- api/src/main/java/com/valtech/aem/saas/api/fulltextsearch/SearchInputModel.java
- core/src/main/java/com/valtech/aem/saas/core/autocomplete/DefaultAutocompleteService.java
- core/src/main/java/com/valtech/aem/saas/core/caconfig/SearchCAConfigurationModelImpl.java
- core/src/main/java/com/valtech/aem/saas/core/fulltextsearch/SearchModelImpl.java
- core/src/main/java/com/valtech/aem/saas/core/fulltextsearch/SearchRedirectModelImpl.java
- core/src/test/java/com/valtech/aem/saas/core/autocomplete/DefaultAutocompleteServiceTest.java
- core/src/test/java/com/valtech/aem/saas/core/fulltextsearch/SearchModelImplTest.java
- core/src/test/java/com/valtech/aem/saas/core/fulltextsearch/SearchRedirectModelImplTest.java
- ui.frontend/src/main/webpack/site/js/searchElement.ts
- add autocomplete switch, autocomplete trigger threshold, autocomplete results max limit CA-configs
- update all implementations where autocomplete is utilized
- update FE search config json validation
- update README file with 'embedding in maven project' instructions
> ICSAAS-431 Enhancements for autocomplete configuration

- ui.frontend/src/main/webpack/site/js/components/searchInput.ts
- ui.frontend/src/main/webpack/site/js/utils/saasStyle.ts
- ui.frontend/src/main/webpack/site/styles/wkndsample/README.md
- ui.frontend/src/main/webpack/site/styles/wkndsample/wkndsample.scss
Wasn't so straightforward prefixing the ID, found an issue lol...
Broken:
Fix:
> fix(ICSAAS-425): fix broken autocomplete popup

- core/src/main/java/com/valtech/aem/saas/core/fulltextsearch/SearchTabModelImpl.java
- core/src/main/java/com/valtech/aem/saas/core/http/response/FacetFieldsDataExtractionStrategy.java
- core/src/main/java/com/valtech/aem/saas/core/http/response/dto/FacetCountsDTO.java
- core/src/test/java/com/valtech/aem/saas/core/fulltextsearch/SearchTabModelImplTest.java
- core/src/test/java/com/valtech/aem/saas/core/http/response/FacetFieldsDataExtractionStrategyTest.java
- core/src/test/resources/__files/search/fulltext/response.json
- core/src/test/resources/content/searchpage/content.json
- fix facet groups rendering order
- add unit tests
> ICSAAS-448 facet config order should be respected

- .github/workflows/maven-deploy.yml
- change github action to run on release branch
- in case push fails have another action which can be run on a tag to publish the artifacts
ICSAAS-505
I need to test but unfortunetaly we will need to merge first as I don't want to change the default branch now
> feature(ICSAAS-505): Optimize Maven Release procedure

- .github/workflows/maven-release.yml
fixed gh action release condition
ICSAAS-505
> fix(ICSAAS-505): fixed gh action release condition

- .github/workflows/main.yml
Update javaversion 17 for sonar
> Update javaversion 17 for sonar

- ui.frontend/src/main/webpack/site/js/buildSearch.ts
- ui.frontend/src/main/webpack/site/js/components/buildSearchClearButton.ts
- ui.frontend/src/main/webpack/site/js/components/searchInput.ts
> Cssd 1867 multiple search fields fix
